In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [ ]:
df = pd.read_csv('/content/house-votes-84.csv')
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 17 columns):
 #   Column                                   Non-Null Count  Dtype 
---  ------                                   --------------  ----- 
 0   Class Name                               435 non-null    object
 1    handicapped-infants                     435 non-null    object
 2    water-project-cost-sharing              435 non-null    object
 3    adoption-of-the-budget-resolution       435 non-null    object
 4    physician-fee-freeze                    435 non-null    object
 5    el-salvador-aid                         435 non-null    object
 6    religious-groups-in-schools             435 non-null    object
 7    anti-satellite-test-ban                 435 non-null    object
 8    aid-to-nicaraguan-contras               435 non-null    object
 9    mx-missile                              435 non-null    object
 10   immigration                             435 non-null    objec

In [ ]:
print(df.columns)


Index(['Class Name', ' handicapped-infants', ' water-project-cost-sharing',
       ' adoption-of-the-budget-resolution', ' physician-fee-freeze',
       ' el-salvador-aid', ' religious-groups-in-schools',
       ' anti-satellite-test-ban', ' aid-to-nicaraguan-contras', ' mx-missile',
       ' immigration', ' synfuels-corporation-cutback', ' education-spending',
       ' superfund-right-to-sue', ' crime', ' duty-free-exports',
       ' export-administration-act-south-africa'],
      dtype='object')


In [ ]:
df

Class Name  handicapped-infants  water-project-cost-sharing  \
0    republican                    n                           y   
1    republican                    n                           y   
2      democrat                    ?                           y   
3      democrat                    n                           y   
4      democrat                    y                           y   
..          ...                  ...                         ...   
430  republican                    n                           n   
431    democrat                    n                           n   
432  republican                    n                           ?   
433  republican                    n                           n   
434  republican                    n                           y   

     adoption-of-the-budget-resolution  physician-fee-freeze  el-salvador-aid  \
0                                    n                     y                y   
1                                    n                     y                y   
2                                    y                     ?                y   
3                                    y                     n                ?   
4                                    y                     n                y   
..                                 ...                   ...              ...   
430                                  y                     y                y   
431                                  y                     n                n   
432                                  n                     y                y   
433                                  n                     y                y   
434                                  n                     y                y   

     religious-groups-in-schools  anti-satellite-test-ban  \
0                              y                        n   
1                              y                        n   
2                              y                        n   
3                              y                        n   
4                              y                        n   
..                           ...                      ...   
430                            y                        n   
431                            n                        y   
432                            y                        n   
433                            y                        ?   
434                            y                        n   

     aid-to-nicaraguan-contras  mx-missile  immigration  \
0                            n           n            y   
1                            n           n            n   
2                            n           n            n   
3                            n           n            n   
4                            n           n            n   
..                         ...         ...          ...   
430                          n           y            y   
431                          y           y            y   
432                          n           n            n   
433                          ?           ?            ?   
434                          n           n            y   

     synfuels-corporation-cutback  education-spending  superfund-right-to-sue  \
0                               ?                   y                       y   
1                               n                   y                       y   
2                               y                   n                       y   
3                               y                   n                       y   
4                               y                   ?                       y   
..                            ...                 ...                     ...   
430                             n                   y                       y   
431                             n                   n                       n   
432                             y           

In [ ]:
df.isna().sum()

Class Name                                 0
 handicapped-infants                       0
 water-project-cost-sharing                0
 adoption-of-the-budget-resolution         0
 physician-fee-freeze                      0
 el-salvador-aid                           0
 religious-groups-in-schools               0
 anti-satellite-test-ban                   0
 aid-to-nicaraguan-contras                 0
 mx-missile                                0
 immigration                               0
 synfuels-corporation-cutback              0
 education-spending                        0
 superfund-right-to-sue                    0
 crime                                     0
 duty-free-exports                         0
 export-administration-act-south-africa    0
dtype: int64

In [ ]:

from sklearn.model_selection import train_test_split


df = df.replace({'n': 0, 'y': 1, '?': None})
df = df.fillna(method='ffill')
df = df.fillna(method='bfill')

df = df.replace({'democrat' : 1, 'republican' : 0})

df = df.astype({col: 'float' for col in df.columns if col != 'Class Name'})

y = df['Class Name'].values
X = df.loc[:, ' handicapped-infants':' export-administration-act-south-africa'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)



<ipython-input-104-fc906ee30cd0>:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')
<ipython-input-104-fc906ee30cd0>:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='bfill')


In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)
answers_pred = model.predict(X_test)

In [ ]:
model.coef_

array([[ 0.27004865,  0.42165096,  1.84584096, -3.44805502, -1.04389033,
         0.2041149 , -0.86454611, -0.07471917,  1.20249408, -0.76527144,
         1.55975765, -0.58854207, -0.22309007, -0.66022097,  0.64919307,
        -0.58587344]])

In [ ]:
model.intercept_

array([2.63658699])

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, answers_pred))

0.9694656488549618


In [ ]:
df['Class Name'].value_counts()

Class Name
1    267
0    168
Name: count, dtype: int64

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

confusion_matrix(y_test, answers_pred)

array([[45,  1],
       [ 3, 82]])

In [ ]:
tn, fp, fn, tp = confusion_matrix(y_test, answers_pred).ravel()
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)
print("TP:", tp)

TN: 45
FP: 1
FN: 3
TP: 82


In [ ]:
accuracy_score(y_test, answers_pred)

0.9694656488549618

In [ ]:
recall_score(y_test, answers_pred)

0.9647058823529412

In [ ]:
precision_score(y_test, answers_pred)

0.9879518072289156

In [ ]:
f1_score(y_test, answers_pred)

0.9761904761904762